# Generated by Django 4.1.7 on 2023-03-25 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("auths", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="primary",
            name="course",
            field=models.ManyToManyField(null=True, to="students.course"),
        ),
    ]
