# Generated by Django 4.1.7 on 2023-03-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
        ("auths", "0002_primary_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="primary",
            name="course",
            field=models.ManyToManyField(to="students.course"),
        ),
    ]
