# Generated by Django 4.1.7 on 2023-04-04 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_topic_course_alter_topic_note_file_alter_topic_notes"),
    ]

    operations = [
        migrations.RemoveField(model_name="topic", name="course",),
        migrations.AddField(
            model_name="course",
            name="topic",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="students.topic",
            ),
        ),
    ]
