# Generated by Django 4.1.7 on 2023-04-04 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_remove_topic_course_course_topic"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic", old_name="note_file", new_name="note_files",
        ),
    ]
