# Generated by Django 4.1.7 on 2023-04-04 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0005_rename_note_file_topic_note_files"),
    ]

    operations = [
        migrations.RenameField(
            model_name="topic", old_name="note_files", new_name="files",
        ),
    ]
