# Generated by Django 4.1.7 on 2023-05-21 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0007_coursetopic"),
    ]

    operations = [
        migrations.RemoveField(model_name="course", name="topic",),
        migrations.AddField(
            model_name="topic",
            name="course",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.course",
            ),
        ),
    ]
