# Generated by Django 4.1.7 on 2023-05-23 08:44

import cloudinary_storage.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_alter_topic_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "files",
                    models.FileField(
                        null=True,
                        storage=cloudinary_storage.storage.RawMediaCloudinaryStorage(),
                        upload_to="",
                    ),
                ),
                ("notes", models.TextField(null=True)),
                (
                    "course",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="students.course",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(model_name="topic", name="course",),
        migrations.DeleteModel(name="CourseTopic",),
        migrations.DeleteModel(name="Topic",),
    ]
